/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;
import Entidades.Alumno;
import Persistencia.AlumnoData;
import java.sql.Date;
import javax.swing.JOptionPane;

public class FormularioAlumnoView extends javax.swing.JInternalFrame {
    private Persistencia.miConexion conexion = new Persistencia.miConexion("jdbc:mariadb://localhost:3306/universidad", "root", "");
    private Persistencia.AlumnoData aluData = new Persistencia.AlumnoData(conexion);
    

    /**
     * Creates new form FormularioAlumnoView
     */
    public FormularioAlumnoView() {
        initComponents();
        jcEstado.setSelected(true);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NombreCompleto = new javax.swing.JLabel();
        jtNombre = new javax.swing.JTextField();
        jcEstado = new javax.swing.JCheckBox();
        bntGuardar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        Formulario = new javax.swing.JLabel();
        Nacimiento = new javax.swing.JLabel();
        jtFechaNac = new javax.swing.JTextField();
        jtDni = new javax.swing.JTextField();
        Documento = new javax.swing.JLabel();

        NombreCompleto.setText("Nombre");

        jcEstado.setSelected(true);
        jcEstado.setText("Estado");

        bntGuardar.setText("Guardar");
        bntGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntGuardarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");

        btnEliminar.setText("Eliminar");

        btnNuevo.setText("Nuevo");

        Formulario.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        Formulario.setText("Formulario Alumnos");

        Nacimiento.setText("Fecha de nacimiento");

        Documento.setText("Documento");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NombreCompleto))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jtNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                        .addComponent(jtFechaNac, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Documento)
                                    .addComponent(jcEstado))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBuscar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(Formulario, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(75, 75, 75))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(bntGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEliminar)
                .addGap(39, 39, 39)
                .addComponent(btnNuevo)
                .addGap(62, 62, 62))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Formulario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreCompleto)
                    .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nacimiento))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Documento)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscar)))
                .addGap(18, 18, 18)
                .addComponent(jcEstado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntGuardar)
                    .addComponent(btnEliminar)
                    .addComponent(btnNuevo))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntGuardarActionPerformed
           try {
        int dni = Integer.parseInt(jtDni.getText().trim());
        String nombre = jtNombre.getText().trim();
        
        // Parsear fecha desde el JTextField (AAAA-MM-DD)
        java.sql.Date fecha = java.sql.Date.valueOf(jtFechaNac.getText().trim());
        boolean estado = jcEstado.isSelected();

        // Crear objeto alumno
        Entidades.Alumno alumno = new Entidades.Alumno(dni, nombre, fecha, estado);

        // Crear la conexión e instanciar el DAO
        Persistencia.miConexion conexion = new Persistencia.miConexion("jdbc:mariadb://localhost:3306/universidad", "root", "");
        Persistencia.AlumnoData aluData = new Persistencia.AlumnoData(conexion);

        // Guardar en MariaDB
        aluData.guardarAlumno(alumno);
        
        javax.swing.JOptionPane.showMessageDialog(this, "Alumno guardado exitosamente.");
        
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "El DNI debe ser un número entero válido.");
    } catch (IllegalArgumentException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Formato de fecha inválido. Usá AAAA-MM-DD (ej: 2002-05-20).");
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar el alumno: " + e.getMessage());
    }
        
    }//GEN-LAST:event_bntGuardarActionPerformed

    // End of variables declaration                              

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Documento;
    private javax.swing.JLabel Formulario;
    private javax.swing.JLabel Nacimiento;
    private javax.swing.JLabel NombreCompleto;
    private javax.swing.JButton bntGuardar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JCheckBox jcEstado;
    private javax.swing.JTextField jtDni;
    private javax.swing.JTextField jtFechaNac;
    private javax.swing.JTextField jtNombre;
    // End of variables declaration//GEN-END:variables
}
